import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { evaluateArtifactPromotionManifest, inspectArtifactPromotionManifestJson, verifyArtifactPromotionManifest } from '../lib/artifact-promotion-proof.mjs'
import { clone, fixture, json } from './helpers.mjs'

test('declared immutable artifact promotion chain passes', async () => { const result = evaluateArtifactPromotionManifest(await fixture()); assert.equal(result.verdict, 'promoted'); assert.equal(result.checks.artifactDigestContinuous, true); assert.equal(result.checks.requiredGatesPassed, true); assert.equal(result.executesDeployment, false) })
test('inspect returns only bounded counts and hashes', async () => { const result = inspectArtifactPromotionManifestJson(json(await fixture())); assert.equal(result.declaredStageCount, 3); assert.equal(result.gateReceiptCount, 5); assert.equal(result.artifactSha256, 'a'.repeat(64)); assert.equal('records' in result, false) })
test('artifact digest drift is rejected', async () => { const input = await fixture(); input.records[2].artifactSha256 = 'b'.repeat(64); assert.equal(evaluateArtifactPromotionManifest(input).checks.artifactDigestContinuous, false) })
test('skipped stage is disclosed', async () => { const input = await fixture(); input.records.splice(1, 1); const result = evaluateArtifactPromotionManifest(input); assert.equal(result.verdict, 'not-promoted'); assert.equal(result.checks.exactStageCount, false) })
test('stage order must match policy', async () => { const input = await fixture(); [input.records[0].stageIdHash, input.records[1].stageIdHash] = [input.records[1].stageIdHash, input.records[0].stageIdHash]; assert.equal(evaluateArtifactPromotionManifest(input).checks.stageOrderMatched, false) })
test('environment binding must match policy', async () => { const input = await fixture(); input.records[1].environmentHash = '3'.repeat(64); assert.equal(evaluateArtifactPromotionManifest(input).checks.environmentMatched, false) })
test('deployment receipt chain must be continuous', async () => { const input = await fixture(); input.records[2].previousDeploymentReceiptSha256 = '6'.repeat(64); assert.equal(evaluateArtifactPromotionManifest(input).checks.receiptChainValid, false) })
test('every required gate must be present once', async () => { const input = await fixture(); input.records[1].gates.pop(); assert.equal(evaluateArtifactPromotionManifest(input).checks.requiredGatesPassed, false) })
test('unexpected gate types fail closed', async () => { const input = await fixture(); input.records[0].gates[0].type = 'unknown-gate'; assert.equal(evaluateArtifactPromotionManifest(input).stages[0].unexpectedGateTypes, true) })
test('distinct gate authority threshold is enforced', async () => { const input = await fixture(); input.records[2].gates[1].authorityHash = input.records[2].gates[0].authorityHash; assert.equal(evaluateArtifactPromotionManifest(input).stages[2].authoritiesDistinct, false) })
test('gate evidence must precede promotion', async () => { const input = await fixture(); input.records[2].gates[0].observedAt = '2026-08-26T04:01:00.000Z'; assert.equal(evaluateArtifactPromotionManifest(input).checks.chronologyValid, false) })
test('stale evidence is disclosed', async () => { const input = await fixture(); input.evaluationTime = '2026-08-28T05:00:00.000Z'; assert.equal(evaluateArtifactPromotionManifest(input).checks.evidenceFresh, false) })
test('secret-shaped values and raw logs are rejected', async () => { const secret = await fixture(); secret.token = 'Bearer abcdefghijklmnopqrstuvwxyz'; assert.throws(() => evaluateArtifactPromotionManifest(secret), { code: 'SECRET_MATERIAL' }); const raw = await fixture(); raw.records[0].log = 'hidden'; assert.throws(() => evaluateArtifactPromotionManifest(raw), { code: 'SECRET_MATERIAL' }) })
test('duplicate gate receipt ids are rejected', async () => { const input = await fixture(); input.records[1].gates[0].gateIdHash = input.records[0].gates[0].gateIdHash; assert.throws(() => evaluateArtifactPromotionManifest(input), { code: 'INVALID_MANIFEST' }) })
test('content-addressed artifact is replay-safe and read back', async () => { const root = await mkdtemp(join(tmpdir(), 'promotion-proof-')); try { await writeFile(join(root, 'manifest.json'), json(await fixture())); const first = await verifyArtifactPromotionManifest({ workspaceRoot: root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); const second = await verifyArtifactPromotionManifest({ workspaceRoot: root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(first.artifact.sha256, second.artifact.sha256); assert.equal(first.artifact.verifiedByReadBack, true); assert.equal(JSON.parse(await readFile(join(root, first.artifact.path), 'utf8')).verdict, 'promoted') } finally { await rm(root, { recursive: true, force: true }) } })
test('path traversal and symlink inputs are rejected', async t => { const root = await mkdtemp(join(tmpdir(), 'promotion-path-')); try { await assert.rejects(() => verifyArtifactPromotionManifest({ workspaceRoot: root, manifestPath: '../outside.json', artifactDir: 'artifacts' }), { code: 'PATH_ESCAPE' }); await mkdir(join(root, 'real')); await writeFile(join(root, 'real', 'manifest.json'), json(await fixture())); try { await symlink(join(root, 'real'), join(root, 'link'), 'junction') } catch { t.skip('unprivileged Windows symlink creation is not portable'); return } await assert.rejects(() => verifyArtifactPromotionManifest({ workspaceRoot: root, manifestPath: 'link/manifest.json', artifactDir: 'artifacts' }), { code: 'UNSAFE_MANIFEST' }) } finally { await rm(root, { recursive: true, force: true }) } })
